### ISSUE TITLE
Report summary and console output have discrepancies

### ISSUE THREAD

**Issue by seaman1** [TrueDub/cucumber-performance#5]
Steps to reproduce:
1. Make few successful runs (for example 4)
2. Delete all runs (Delete Build - in Jenkins terms) from Jenkins .
3. Make new run.

Console output after run:
```
[CucumberPerfRecorder] running project reports on 1 builds
```
Summary results shows result for 4 runs (results before runs where deleted).

**Comment by TrueDub** [comment]
Due to pressures of time, along with lack of access to a large-scale Cucumber project to facilitate testing, I'm no longer in a position to maintain this project. Thank you for your feedback.

If required, I suggest you open an issue on the jenkinsci repo page for the plugin - https://github.com/jenkinsci/cucumber-performance-plugin
