### ISSUE TITLE
[Improvement] Performance reports should contain "Last duration" column

### ISSUE THREAD

**Issue by seaman1** [TrueDub/cucumber-performance#6]
Performance reports contains 3 columns: "Shortest Duration", "Longest Duration", "Average Duration". 
This information doesn't give me a possibility to analyse if product performance increased/decreased. As for me this is main reason of why we need track /analyse performance. 
My proposition is to add  "Last duration" column after "Average Duration" column.
This gives me a possibility to understand what is current product performance.
Additional feature: highlight tests with colour which have more then 50% run difference with average run (green - if last run is 50% shorter than average and red - if last run is 50% longer than average).

**Comment by TrueDub** [comment]
Due to pressures of time, along with lack of access to a large-scale Cucumber project to facilitate testing, I'm no longer in a position to maintain this project. Thank you for your feedback.

If required, I suggest you open an issue on the jenkinsci repo page for the plugin - https://github.com/jenkinsci/cucumber-performance-plugin
