### ISSUE TITLE
No Data exists for test runs" message on successful Performance Report generation

### ISSUE THREAD

**Issue by olliec** [TrueDub/cucumber-performance#7]
Hi,

On an apparently successful generation of Cucumber performance reports I get the message when attempting to view report.
![image](https://cloud.githubusercontent.com/assets/177904/4009542/fc24d712-29e5-11e4-9999-70640178a3d3.png)

Cucumber reports themselves were generated successfully.

From the logs:
[CucumberPerfRecorder] Starting Cucumber Performance Report generation...
[CucumberPerfRecorder] Reporting on performance for PROJNAME-tests #3000
[CucumberPerfRecorder] detected slave build 
found files 
found files
.................469 other instances of found files
found files
[CucumberPerfRecorder] running project reports on 2 builds
[CucumberPerfRecorder] project report generation complete
Recording fingerprints

---------
On a test instance of jenkins where build was master we successfully generated a report.
Any idea what the issue could be?

**Comment by TrueDub** [comment]
Due to pressures of time, along with lack of access to a large-scale Cucumber project to facilitate testing, I'm no longer in a position to maintain this project. Thank you for your feedback.

If required, I suggest you open an issue on the jenkinsci repo page for the plugin - https://github.com/jenkinsci/cucumber-performance-plugin
